### PR TITLE
This is a complete recoloring of the site, in order to make it match better with the Severance colors.

### PR DESCRIPTION
**Pull request by rexaril**
No other changes were made besides recoloring and changing the fonts. This should match better with Severance.

### CODE REVIEW

**Comment by shiffman** [comment]
Wow, this pull requests exceeds quota, waffle parties all around!

I had made some updates to the images which didn't make it through with your changes unfortunately. Are you able to take a look at those? Also, I wonder if the color shift can be a slightly more subtle / darker blue? Maybe I'm just too used to looking at it black!

**Comment by rexaril** [comment]
> Wow, this pull requests exceeds quota, waffle parties all around!
> 
> I had made some updates to the images which didn't make it through with your changes unfortunately. Are you able to take a look at those? Also, I wonder if the color shift can be a slightly more subtle / darker blue? Maybe I'm just too used to looking at it black!

Done! :D

**Comment by shiffman** [comment]
Strange, do you know why this is still showing conflicts? I will try to take a look later today!

**Comment by shiffman** [comment]
Many apologies, I'm sorry we weren't able to get this to work, but we now have more visual accuracy with #20! Thank you so much for taking the time to contribute and participate in this project! ❤️

**Pull request closed without merging**
