### PR TITLE
Feature: CRT Shader Pass

### PR DESCRIPTION
**Pull request by jhrtn**
for https://github.com/Lumon-Industries/Macrodata-Refinement/issues/19

Issues:

- it's very slow! (I'm guessing like 5-10FPS right now) I'm taking a copy of the canvas context at the end of the draw loop, passing that into the shader as a sampler2D texture and then drawing that output to the screen. Maybe this would be improved by using an offscreen canvas?
- Everything seems to be 4x zoomed in, I could only take the above screen recording by zooming out my Chrome window to 50% (that's why the bins at the bottom look so small)
- When a modal image is drawn to the screen it shoots up to the top left, I think a push()/pop() must be messing things up somewhere, the MDE moment is fine though

https://user-images.githubusercontent.com/17256474/162533764-5783a306-dbcc-4c90-bb04-f6c49552591a.mov

### CODE REVIEW

**Comment by shiffman** [comment]
Wow, this is so exciting! It looks amazing! I think the speed is a bit of a dealbreaker but hopefully we can figure out a way! We could also do some checking and only load it on certain devices / machines that can handle it?

**Comment by jhrtn** [comment]
The shader is pretty lightweight so I think it could run fine and it's more to do with how I've got it set up right now, I'll do more of an investigation tomorrow

**Comment by jhrtn** [comment]
Couple of updates on this:

- Fixed the 'Nope' modal alignment by adding `imageMode(CORNER);` right before I draw the shader output to canvas.
- The 4x zoom issue only occurs on my retina screen. I can fix this by multiplying the width, height by pixel density when I get the image data from canvas context
- Attempted to draw everything to an offscreen p5.Graphics instance rather than directly to the canvas, thinking that it would improve the fps if it wasn't drawn the screen (only to be drawn over by the shader image) this actually made performance worse 
- the performance is much better on my non-retina screen, I get 30-40 fps rather than 10-15fps (with no shader it's max 60fps)

A potential solution for this performance bottleneck would be to reduce the size of the canvas, and upscale when drawing back the shader, as the interface is emulating an older display this might be OK, or may even look good! I'll give this a go and see what the performance is like

**Comment by shiffman** [comment]
what happens if you include `pixelDensity(1)` to force the pixel density regardless of retina vs. non retina? If the idea is to make it older / CRT looking we could also use a lower resolution canvas (always 800x600 for example) and upscale to the browser window when drawing with the shader?

I would like this to continue to work on mobile so we should probably test before merging!

Is there a way to query for compatible browser than skip the shader if not?

**Comment by jhrtn** [comment]
`pixelDensity(1)` fixes the zoomed out issue on retina screens!

My idea for the lower res canvas was to draw everything to a p5 graphics element at a lower resolution, then scale it up to the full screen width when drawing the shader output to the main canvas.

Whilst doing this I tried passing the graphics buffer directly into the shader for the texture uniform instead of using `ctx.getImageData(0, 0, width, height)` - instantly the performance improved to 60fps! Looks like that was the bottleneck

I haven't done any testing on mobile but you can have a try at this link: https://macrodata-refinement-3ucu5kw7h-jhrtn.vercel.app/

**Comment by shiffman** [comment]
Awesome, will do some tests! On iOS I'm getting only about 12 FPS 😢. Does adding the curvature of the monitor affect performance? If so, I would probably be ok with losing that and just keep the fuzzy monitor look?

**Comment by jhrtn** [comment]
It all takes place within the same shader so I don't think it affects performance that much, but I'll test that out, the overall effects seems a bit much on mobile! I think it needs to respond the screen resolution better.

Could you try this version? This is the latest code from your main branch, with the FPS monitor. I'm getting about 20-25 fps on my Pixel 5
[macrodata-refinement-git-test-fps-monitor-jhrtn.vercel.app](https://macrodata-refinement-git-test-fps-monitor-jhrtn.vercel.app/)

Then with [the shader version](https://macrodata-refinement-git-feature-crt-shader-jhrtn.vercel.app/) I'm getting about 18-23 fps (also updated from main with the bin animations)

**Comment by shiffman** [comment]
> Could you try this version? This is the latest code from your main branch, with the FPS monitor. I'm getting about 20-25 fps on my Pixel 5

On iOS (iphone 12 pro) I get 60 FPS on the "plain" version and ~12 FPS on the shader version. It kind of fits at lower frameRate b/c it feels more like an old computer but I think a minimum of 20 FPS would be a good goal?

**Comment by shiffman** [comment]
Also, FYI the GIFs at 75% data don't play for me. Can investigate later too!

**Comment by jhrtn** [comment]
I tried halving the width and height in the graphics object, then upscaling the shader output - got about 30fps on iPad, but could not see any output, on my Pixel 5 I got 2 fps 😬  This also presents the issue that the cursor position also needs to be scaled. I could achieve this by hiding the native cursor on the canvas and drawing a one at the correct position, however on touchscreen this won't work (we can't scale the user's finger position!)

For now I've added a mobile device check, and the shader isn't used if on mobile: [macrodata-refinement-2dycs6l0t-jhrtn.vercel.app](https://macrodata-refinement-2dycs6l0t-jhrtn.vercel.app/)

Regarding the gif not playing in the graphics object, seems like it was a known issue that was fixed: https://github.com/processing/p5.js/issues/4421 - if I switch the p5js version to 1.1.3 the gif plays, but something changed from 1.3.0 onwards and the problem exists again

edit: this issue could also be relevant: https://github.com/processing/p5.js/issues/5511

I can fix this issue by manually incrementing the gif frame with
```js
    const currGifFrame = frameCount % mdeGIF[0].gifProperties.numFrames
    mdeGIF[0].setFrame(currGifFrame);
```

or if we wanted offset the frames in the loop we could do: 
```js
 for (let i = 0; i < dim; i++) {
    let xoff = 100;
    for (let j = 0; j < dim; j++) {
      const currGifFrame = (frameCount + (i+j)) % mdeGIF[0].gifProperties.numFrames;
      mdeGIF[0].setFrame(currGifFrame);
  ...
  }
}
```

https://user-images.githubusercontent.com/17256474/162974742-1a0418c3-cd15-45dd-91df-4907948646c4.mov

**Comment by shiffman** [comment]
Amazing! Yes, I wanted to offset all the GIFs looping I think that's a cool effect. My test just now I got 60 FPS on my macbook pro! And mobile it reverts to the plain version! I think we should at least color the mobile slightly blue to match the look a bit?

**Comment by jhrtn** [comment]
Yes good point, I should be able to look at that later this evening 👍

**Comment by jhrtn** [comment]
Finally had a chance to come back and look at this. Tweaked the colour palette for shader & non-shader usage, I've also created a toggle when you click on the Lumon logo, thought this might be helpful for testing, should I leave this in the PR?

Things that aren't perfect: the modals + lumon logo background don't change, perhaps these could be SVGs or drawn in p5 rather than be pngs.

try it here: https://macrodata-refinement-git-feature-crt-shader-jhrtn.vercel.app/

https://user-images.githubusercontent.com/17256474/164483871-b784a401-d330-4505-82e2-b47cd7a4ee37.mp4

**Comment by shiffman** [comment]
This is working great btw! @jhrtn should we try integrating it?

**Comment by jhrtn** [comment]
Yes I think we're ready to go! I've updated the branch with:
- Merged the latest changes in, fixed conflicts with the local storage feature
- Tweaked the non-shader colours to more closely match the shader + show reference
- Removed the toggle shader behaviour when the Lumon logo is clicked
- Removed the FPS counter

Think this is everything?

**Comment by shiffman** [comment]
Amazing!! I'm going to merge, play around with it, and will make any changes as needed!

**Pull request merged**
