### PR TITLE
Update starter.frag

### PR DESCRIPTION
**Pull request by kfahn22**
Cleaned up code by deleting unused functions.
Added clouds.
Changed mountain code so height of initial mountains decrease with iTime to fake panning in z plane.  
Changed the mix function to decrease CRT effect.

https://editor.p5js.org/kfahn/full/zTlO7Y61I

### CODE REVIEW

**Comment by shiffman** [comment]
Oh man, this is looking so good! I was thinking this could just appear behind the share button? @jhrtn let me know what you think!

**Comment by kfahn22** [comment]
I am taking another crack at have true 3D mountains.  I have taken some of  IQ's base code from the Happy Jumping tutorial and played around with it.   I have the base down, but still trying to work out how to introduce randomness to the mountains without introducing distortions.  What is really like is the way the camera pans through the scene.  If we can introduce randomness, it would be great.  Here is a version without all the other stuff.  Please let me know what you think.

https://editor.p5js.org/kfahn/full/FCG-t1BIh

**Comment by shiffman** [comment]
Wow, that looks cool! I do like the flat, kind of retro aesthetic though so I don't you necessarily need to feel like it needs to be "fancier". Also there is the question of what will / won't run on mobile! Have you tested any of these sketches  on mobile?

**Comment by kfahn22** [comment]
I think you make a very good point re retro 2D.  I just wished I could figure out how to introduce the nice camera panning that the 3D one has.  BTW, I just checked the 2D sketch on my old iPad and noticed that changing one of the vignette parameters has introduced a triangle into the scene.  I will try to fix that later today or maybe  a different CRT code would be better.  I also just checked the 2D scene on my phone.  I did have to adjust  the screen size so that the whole canvas showed. How is the screen size set for the data mining code?

**Comment by jhrtn** [comment]
> Oh man, this is looking so good! I was thinking this could just appear behind the share button? @jhrtn let me know what you think!

sounds good! Can separate sketch files be embedded in their own p5 graphics object?

**Comment by kfahn22** [comment]
I am not sure why I was seeing a stray triangle--I just reran the sketch  and I think it is ok.  You originally wanted music and a computerized voice saying "I love you", which I think are nice touches.  Also maybe  adding  "I knew you could do it"  would be nice.  Alternately, maybe the  scene could end  with "I love you"  written in the sky.  Is there a way to incorporate sound easily?  Also wondering if we could add this as an asset.

**Comment by kfahn22** [comment]
I have incorporated the scanline code that @jhrtn used in the crt shader.  (Nice job, Joseph!)  I think it is an improvement -- what do you think?

https://editor.p5js.org/kfahn/full/uFAfUBxR-

**Comment by shiffman** [comment]
> sounds good! Can separate sketch files be embedded in their own p5 graphics object?

I was thinking we probably just need to manually keep track of state and switch to drawing this sequence at 100% via if statements essentially. I can try to take a look later today and see what might work best!

> You originally wanted music and a computerized voice saying "I love you", which I think are nice touches. Also maybe adding "I knew you could do it" would be nice. Alternately, maybe the scene could end with "I love you" written in the sky. Is there a way to incorporate sound easily?

The easiest thing would to be use p5.sound and just play mp3 files, maybe we start with that! If we wanted to get fancy we could use p5.speech to speak a custom message each time.

**Comment by kfahn22** [comment]
Sounds good--simpler is usually best.  Although, it has occurred to me that suddenly introducing sound might end up being disruptive (for example, if a kid was playing in a classroom.)

I have added a couple more clouds (in a really inefficient way), edited colors and layers a bit, and tried to improve the pan in.
Here is latest version:  https://editor.p5js.org/kfahn/full/uFAfUBxR-

Aside from adding more clouds or editing colors, I think that this is close to done.  Please let me know if you think there is anything else the needs attention.

**Comment by kfahn22** [comment]
I just added the p5.speech library to the sketch, but  I can only get the default voice to work.  I have it saying  "I knew you could do it.  You have brought glory to the company.  I love you."   I have also tried to speed up the animation so that it ends about the same time.


https://editor.p5js.org/kfahn/full/i3yevkWlR

**Pull request closed without merging**
